---
name: TF CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"

jobs:
  tflint:
    name: Terraform lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opstree/central-github-actions/terraform/linters@main
        with:
          terraform_version: "1.10.2"
          directory: "./"
